### ISSUE TITLE
rechat subtitle tracks missing in Twitch VODs.

### ISSUE THREAD

**Issue by sbstratos79** [CrendKing/mpv-twitch-chat#2]
Windows 10. 
curl 7.55.1 (Windows) libcurl/7.55.1 WinSSL
mpv 0.33.0-228-g1e90ec647c
FFmpeg library versions:
   libavutil       57.0.100
   libavcodec      59.3.101
   libavformat     59.4.100
   libswscale      6.0.100
   libavfilter     8.0.103
   libswresample   4.0.100
FFmpeg version: git-2021-07-18-694545b6

Twitch VODs don't load any rechat subtitle tracks so mpv-twitch-chat doesn't work.

**Comment by CrendKing** [comment]
Log please.

**Comment by sbstratos79** [comment]
Here's the log.
[mpvtwitch.log](https://github.com/CrendKing/mpv-twitch-chat/files/6874133/mpvtwitch.log)

**Comment by CrendKing** [comment]
I see you are trying to watch a LIVE stream. Live stream's chat is in a completely different platform (IRC), not static JSON file. Technically we can add support for it, but not at the moment. This filter only supports VOD (past broadcast).

Fortunately, if a channel is currently live, most channel's latest "past broadcast" is exactly that stream. The only problem is that unlike live, the video will not dynamically expand, so you need to refresh from time to from.

**Comment by sbstratos79** [comment]
Thanks. For some reason I just assumed it would work with live broadcasts as well. Guess I was mistaken.
