### ISSUE TITLE
Paused VODs make the subtitle timings to drift beyond the current timestamp

### ISSUE THREAD

**Issue by garoto** [CrendKing/mpv-twitch-chat#3]
I'm guessing because the script will continue to fetch new segments regardless of the player state. Any seek ammount forward(?) or backwards will resync the subs. Perhaps adding a timer that observes the pause property and suspending fetching new segments might be a fix? Thinking some function similar to this:

```lua
local save_period_timer = mp.add_periodic_timer(o.save_period, save)

local function pause(name, paused)
	save()
	if paused then
		save_period_timer:stop()
	else
		save_period_timer:resume()
	end
end

mp.observe_property("pause", "bool", pause)

```

Above from the script located here: https://gist.github.com/CyberShadow/2f71a97fb85ed42146f6d9f522bc34ef

I wish I could propose a more comprehensive lua solution, but I'm not a computer programmer.

**Comment by CrendKing** [comment]
https://github.com/CrendKing/mpv-twitch-chat/commit/3d8ce579f84915bcd9a396658acf65a1ae1bdec8

**Comment by garoto** [comment]
Works, thanks.
