### ISSUE TITLE
Add support for Youtube chat replay for premiers/livestream vods

### ISSUE THREAD

**Issue by BanchouBoo** [CrendKing/mpv-twitch-chat#7]
Similar to Twitch vods, [yt-dlp](https://github.com/yt-dlp/yt-dlp) includes a `live_chat.json` subtitle file with all the information for the chat messages, would be very nice to have

**Comment by CrendKing** [comment]
I can take a look. Any sample URL?

**Comment by BanchouBoo** [comment]
https://youtu.be/O4oixjzvrZk

**Comment by CrendKing** [comment]
It seems, unlike Twitch, Youtube does not provide a direct API to get the live chat JSON. Instead, yt-dlp has [this 200-line Python script](https://github.com/yt-dlp/yt-dlp/blob/99e9e001de8a4106654d7a20757cae725a5ac0c3/yt_dlp/downloader/youtube_live_chat.py) to parse and download the chat JSON fragments. I'm not planning to rewrite this into Lua and maintain it up-to-date. Sorry.

**Comment by BanchouBoo** [comment]
In case anyone stumbles across this in the future, I decided to make it myself: https://github.com/BanchouBoo/mpv-youtube-chat

**Comment by CrendKing** [comment]
Thanks for sharing. I quite like the way you scroll the messages interactively. However, I think Twitch's GQL API now aggregates messages in a more coarse time granularity, which might make the scrolling less enticing.
