### ISSUE TITLE
This API does not exist

### ISSUE THREAD

**Issue by NaiveInvestigator** [CrendKing/mpv-twitch-chat#9]
When playing a VOD is gives me this error, How do i fix this?

```
[mpv_twitch_chat] Failed to download comments JSON: {"error":"Not Found","status":404,"message":"This API does not exist"}
```

**Comment by CrendKing** [comment]
The VOD chat replay API is undocumented and not recommended for "public use". Recently Twitch disabled this API for all but certain client ID(s). You need to specify the correct client ID in the option file of this script. For legal reason I can't tell you what ID you should use. Sorry.

**Comment by NaiveInvestigator** [comment]
> The VOD chat replay API is undocumented and not recommended for "public use". Recently Twitch disabled this API for all but certain client ID(s). [You need to specify the correct client ID in the option file of this script](https://github.com/CrendKing/mpv-twitch-chat/commit/0954291b175ddd33e1ab31539ceab3a80dc5b8bf). For legal reason I can't tell you what ID you should use. Sorry.

Oh tysm! This clears up the problem then. Sucks that we can't use it anymore :<. But what was their reasoning for doing this tho?

**Comment by CrendKing** [comment]
Legally, I can only recommend you to go to their feedback forum and vote for a new official API for VOD chat, such as [this](https://twitch.uservoice.com/forums/310213-developers/suggestions/44063160-vod-chat-for-helix), though the chance is extremely slim.

However, if you happen to know the client ID required to access the API, the API, at the moment of writing, is still working.
